source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RichTextVC-iOS-Example', :exclusive => true do
  pod 'RichTextVC-iOS', :path => '../'
end

target 'RichTextVC-iOS-Tests', :exclusive => true do
  pod 'RichTextVC-iOS', :path => '../'
end


