source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!


target 'RichTextVC-iOS-Example' do
  pod 'RichTextVC-iOS', :path => '../'
end

target 'RichTextVC-iOS-ExampleTests' do
    pod 'RichTextVC-iOS', :path => '../'
end

target 'RichTextVC-iOS-Tests' do
  pod 'RichTextVC-iOS', :path => '../'
end
