source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'RichTextVC-iOS-Example' do
  pod 'RichTextVC-iOS', :path => '../'
end

target 'RichTextVC-iOS-ExampleTests' do
    pod 'RichTextVC-iOS', :path => '../'
end

target 'RichTextVC-iOS-Tests' do
  pod 'RichTextVC-iOS', :path => '../'
end
